name: CI Pipeline

on:
  pull_request:
    branches:
      - master
      - development
    types:
      - opened
jobs:
  docker:
    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: rytry/modul_324_lb1:latest
